/* config.js — generated by the build. Public settings only: the Supabase anon key is designed to be public. */
window.APP_CONFIG = {
  "slug": "resume-analyzer",
  "name": "Resume Match",
  "supabaseUrl": "",
  "supabaseAnonKey": "",
  "aiProxy": "",
  "google": false,
  "prompts": [
    {
      "say": "Score my resume against this job posting",
      "does": "Runs the match and shows missing keywords."
    },
    {
      "say": "Rewrite my weakest three bullets with numbers",
      "does": "Finds the lowest-scoring bullets and rewrites them."
    },
    {
      "say": "Write a short cover letter for this role",
      "does": "Drafts a letter from your resume and the job."
    }
  ]
};
